import { Project } from "@/types";

export const MOCK_PROJECTS: Project[] = [
  {
    id: "1",
    title: "SolarOS Dashboard",
    organization: "Helios Energy Labs",
    description: "A revolutionary energy grid visualizer for autonomous micro-grids. We are scaling our energy storage calculations and need experts.",
    owner_id: "user_1",
    category: "Sustainability",
    skills_required: ["React", "D3.js", "WebSockets", "Go"],
    tags: ["ANIMATION", "REAL-TIME SYSTEMS", "DATA VIS"],
    max_team_size: 6,
    current_members_count: 4,
    status: "open",
    created_at: "2026-03-20T00:00:00Z",
    deadline: "NOV 20",
  },
  {
    id: "2",
    title: "Sentience AI Agent",
    organization: "NeuralFlow",
    description: "An open-source framework for building multi-modal AI agents that can browse the web and execute local scripts. Focused on extreme autonomy.",
    owner_id: "user_2",
    category: "AI/ML",
    skills_required: ["Gemini API", "Rust", "Python", "WASM"],
    tags: ["LLM OPS", "RUST", "SECURITY"],
    max_team_size: 20,
    current_members_count: 12,
    status: "open",
    created_at: "2026-03-22T00:00:00Z",
    deadline: "DEC 1",
  },
  {
    id: "3",
    title: "Vault Protocol v2",
    organization: "VaultDAO",
    description: "Next-generation lending protocol with dynamic collateralization. Looking for auditors and frontend engineers to build a seamless Pro dashboard.",
    owner_id: "user_3",
    category: "Web3",
    skills_required: ["Solidity", "Viem", "Wagmi", "Next.js"],
    tags: ["SOLIDITY", "MATH", "FINTECH"],
    max_team_size: 10,
    current_members_count: 3,
    status: "open",
    created_at: "2026-03-25T00:00:00Z",
    deadline: "DEC 10",
  },
];
